name = "heartstopper"
main = "src/index.js"
compatibility_date = "2023-04-25"

kv_namespaces = [
  { binding = "SETTINGS", id = "be64850ed0694a8f9f218f8690d73134", preview_id="be64850ed0694a8f9f218f8690d73134" }
]

[triggers]
crons = ["0 9 * * *"]

[vars]
ORIGIN="https://heartstopper.blackcatjackster6975.workers.dev"

# SECRETS:
# DISCORD_APPLICATION_ID
# DISCORD_PUBLIC_KEY
# DISCORD_SECRET
# DISCORD_TOKEN